### ISSUE TITLE
XCVM Spec questions

### ISSUE THREAD

**Issue by kkx** [ComposableFi/composable#1602]
This is thread for asking spec related questions
](https://github.com/ComposableFi/composable/blob/cfc127c772938a0f6c936ae5076db48c006963e8/code/xcvm/SPEC.md?plain=1#L201)

Shouldn't include the destination address here as part of the transfer parameter? if so, should be bytes and in the interpreter side, each of those implementations may need to convert it to its own valid type(address in evm), am I right?

**Comment by hussein-aitlahcen** [comment]
Yes, the implementation require an address as specified in the variant `Account Assets`, with `Account` being a locally encoded public key. The `Account` is a raw payload that the interpreter must decode into a local account (i.e. the size of a public key depends on the chain, hence it's a dynamic array of bytes).

**Comment by dzmitry-lahoda** [comment]
I do not know. we had proto file which had u128 = low : 64;  high :u64. No sure where it is.

**Comment by dzmitry-lahoda** [comment]
> should the payload include the address/contract to interact with?
yes. but it is encoded into blob payload.

**Comment by dzmitry-lahoda** [comment]
[xcvm.proto](https://github.com/ComposableFi/composable/blob/xcvm-main/lib/xcvm/protobuf/src/xcvm.proto)

**Comment by dzmitry-lahoda** [comment]
xcvm spec != proto spec. so representaionof 128 bit number can be irrlevant detail.

**Comment by hussein-aitlahcen** [comment]
Good catch, my take is that we should update the spec with the binding variant `Amount` being replaced `AssetId Balance` such that we do have the asset we ask the ratio for in the context of late binding.

**Comment by dzmitry-lahoda** [comment]
>  According to the definition, the actual amount decoded from the Ratio type would be the percentage of the balance in the interpreter contract. 
> To get the erc20 token balance of the interpreter, the information of {1} is needed to be decoded beforehand and put in the ratio decoder. but if we do so, it may not be generic enough since not all these operations are Erc20 token related.

Not sure what conflict is there. {1} and {2} unrelated. {2} is always amount from well know token contract of well know interpreter? So if somebody puts into {1} interpreter address why would we care? we care is that {2} is from well know and managed by owner (router).

**Comment by dzmitry-lahoda** [comment]
So our interpreter account will have its relevant amount in 10 different foobar20 assets . It will mean that our interpreter supports foobar20 to foobar20 transfer and there are 10 foobar20 instances and interpreter may have amounts in these. it cannot have in others as we support only what we support or what was registered into us. so {1} will be foobar20 compatible, so can call it to get to know what amount foobar20 at 1 has for interpreter and because {1} before {2} ration we have {1} known before and can find out absolute for ration without adding asset id as data because you cannot transfer amount to contract not used by interpreter to store value.

so what I say that `transfer 10% USDT to Alice form XCVM` is solvable without saying `transfer 10% USDT to Alice from XCVM USDT(see we repeat it here)` because in both case.

while suggested fix may lead
```
`transfer 10% USDT to Alice form XCVM SHIT
```

**Comment by dzmitry-lahoda** [comment]
another note, there are not so much token contracts on each chain. likely maximal is 2. so we can just know all ABIs of these. not big deal.

**Comment by dzmitry-lahoda** [comment]
oh, but if do other things like swap - yeah - it will fail. so yes - my fix will not work.
