### ISSUE TITLE
Centauri IBC Wasm Hooks middleware implemented according spec

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/composable#3953]

**Comment by blasrodri** [comment]
We need to understand, what's specifically missing based on the needs. I don't think anybody really tried to implement wasmhooks on pallet-ibc yet. So we would be open to support this. However, further info needs to be provided before jumping onto an implementation.

For us, who are not developing this, it would be helpful to have:
- an example that's currently not working with the expected behavior
- a diagram of the flow of a packet that successfully works

**Comment by dzmitry-lahoda** [comment]
yeah, example would be awesome what is not working

**Comment by dzmitry-lahoda** [comment]
So request is not Wasm hook. Forgot about, or event PFM. But ICS30 middleware, Wasm hook, PFM, ICS 31 Fee, are all just examples of ICS30 hook, XCM termination is also example of ICS30 middleware btw.

I will provide interface ported from go as example of middleware.

**Comment by dzmitry-lahoda** [comment]
replaced with this https://github.com/ComposableFi/composable/issues/3958

so we do not do empahsis on how Wasm uses middleware, because middleware does not depend on specific usage, XCM/WASM/PFM, it is just works on any packet handling
